[tools]
"forgejo:forgejo-contrib/forgejo-cli" = "latest"
node = "24"
"npm:@nubjs/nub" = "latest"
pnpm = "11"

[shell_alias]
bumpp = "nub exec bumpp" # May be removed if changeset DTRT.
changeset = "nub exec changeset"
eslint = "nub run eslint"
knip = "nub run knip"
tsc = "nub run tsc"
rolldown = "nub run rolldown"
attw = "nub run attw"
e18e = "nub run e18e"
e18e-cli = "nub run e18e"
publint = "nub run publint"
serve = "nub run serve"

