version = 1
SPDX-PackageName = "fedi-any-page"
SPDX-PackageSupplier = "Curtis Jewell <swordsman+aptypescript@curtisjewell.name>"
SPDX-PackageDownloadLocation = "https://git.sr.ht/~csjewell/fedi-any-page"

# Editor configuration.
[[annotations]]
path = [".vscode/**.json", ".editorconfig"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Build configuration files
[[annotations]]
path = ["mise.toml",".common/**","patches/*.patch","**/.npmrc", "**/tsconfig.json", ".config/tsconfig.*.json", "**/package.json", "**/pnpm-*.yaml", "**/deno.jsonc", "**/jsr.jsonc"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Documentation
[[annotations]]
path = "**.md"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Repository configuration files
[[annotations]]
path = [".github/**", "**/.git*"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Web assets.
[[annotations]]
path = ["**/assets/**", "**/index.html"]
SPDX-FileCopyrightText = "2025 Curtis Jewell and other contributors"
SPDX-License-Identifier = "MIT"

# Scripts to help things out.
[[annotations]]
path = ["bin/**"]
SPDX-FileCopyrightText = "2025 Curtis Jewell and other contributors"
SPDX-License-Identifier = "MIT"

# Configuration and test data.
[[annotations]]
path = ["**/*.config.*", "**/*.ts.snap", "**/test_data/**", "**/replytesting.json"]
SPDX-FileCopyrightText = "2025 Curtis Jewell and other contributors"
SPDX-License-Identifier = "MIT"

# SQL file.
[[annotations]]
path = "packages/database-cloudflare-d1/schema.sql"
SPDX-FileCopyrightText = "2025 Curtis Jewell and other contributors"
SPDX-License-Identifier = "MIT"




