/* SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2025 Curtis Jewell and other contributors
 */
import sonarjs from 'eslint-plugin-sonarjs'
import type { ConfigArray } from 'typescript-eslint'

/**
 * Define the configuration for the sonarjs plugin.
 */
const SonarConfig: ConfigArray = [
  {
    files   : ['**/*{js,ts}'],
    plugins : { sonarjs, },
    rules   : {
      // ...sonarjs.configs.recommended.rules,

      'sonarjs/anchor-precedence'                    : 'error',
      'sonarjs/argument-type'                        : 'off',
      'sonarjs/arguments-order'                      : 'warn',
      'sonarjs/arguments-usage'                      : 'warn',
      'sonarjs/array-callback-without-return'        : 'error',
      'sonarjs/array-constructor'                    : 'warn',
      // I need to fix this one before I turn it on.
      'sonarjs/arrow-function-convention'            : 'off',
      'sonarjs/assertions-in-tests'                  : 'off',
      // All aws rules are off, since I don't use aws.
      'sonarjs/aws-apigateway-public-api'            : 'off',
      'sonarjs/aws-ec2-rds-dms-public'               : 'off',
      'sonarjs/aws-ec2-unencrypted-ebs-volume'       : 'off',
      'sonarjs/aws-efs-unencrypted'                  : 'off',
      'sonarjs/aws-iam-all-privileges'               : 'off',
      'sonarjs/aws-iam-all-resources-accessible'     : 'off',
      'sonarjs/aws-iam-privilege-escalation'         : 'off',
      'sonarjs/aws-iam-public-access'                : 'off',
      'sonarjs/aws-opensearchservice-domain'         : 'off',
      'sonarjs/aws-rds-unencrypted-databases'        : 'off',
      'sonarjs/aws-restricted-ip-admin-access'       : 'off',
      'sonarjs/aws-s3-bucket-granted-access'         : 'off',
      'sonarjs/aws-s3-bucket-insecure-http'          : 'off',
      'sonarjs/aws-s3-bucket-public-access'          : 'off',
      'sonarjs/aws-s3-bucket-server-encryption'      : 'off',
      'sonarjs/aws-s3-bucket-versioning'             : 'off',
      'sonarjs/aws-sagemaker-unencrypted-notebook'   : 'off',
      'sonarjs/aws-sns-unencrypted-topics'           : 'off',
      'sonarjs/aws-sqs-unencrypted-queue'            : 'off',
      'sonarjs/bitwise-operators'                    : 'error',
      'sonarjs/block-scoped-var'                     : 'warn',
      'sonarjs/bool-param-default'                   : 'warn',
      'sonarjs/call-argument-line'                   : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/certificate-transparency'             : 'warn',
      'sonarjs/chai-determinate-assertion'           : 'off',
      'sonarjs/class-name'                           : 'warn',
      'sonarjs/class-prototype'                      : 'off',
      'sonarjs/code-eval'                            : 'error',
      // TODO: Check this one, but it probably stays off.
      'sonarjs/cognitive-complexity'                 : 'off',
      'sonarjs/comma-or-logical-or-case'             : 'error',
      'sonarjs/comment-regex'                        : 'off',
      'sonarjs/concise-regex'                        : 'warn',
      'sonarjs/conditional-indentation'              : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/confidential-information-logging'     : 'off',
      'sonarjs/constructor-for-side-effects'         : 'error',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/content-length'                       : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/content-security-policy'              : 'off',
      'sonarjs/cookie-no-httponly'                   : 'warn',
      'sonarjs/cookies'                              : 'off',
      'sonarjs/cors'                                 : 'warn',
      'sonarjs/csrf'                                 : 'warn',
      // TODO: Turn this one on - but have to find out how to configure it.
      'sonarjs/cyclomatic-complexity'                : 'off',
      // Double-check this one.
      'sonarjs/declarations-in-global-scope'         : 'off',
      'sonarjs/deprecation'                          : 'warn',
      'sonarjs/destructuring-assignment-syntax'      : 'warn',
      'sonarjs/different-types-comparison'           : 'warn',
      'sonarjs/disabled-auto-escaping'               : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/disabled-resource-integrity'          : 'off',
      // I don't use Mocha, so it's not of benefit
      'sonarjs/disabled-timeout'                     : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/dns-prefetching'                      : 'off',
      'sonarjs/duplicates-in-character-class'        : 'warn',
      'sonarjs/elseif-without-else'                  : 'off',
      'sonarjs/empty-string-repetition'              : 'error',
      'sonarjs/encryption'                           : 'error',
      'sonarjs/encryption-secure-mode'               : 'warn',
      // @stylistic/comma-dangle is equivalent to enforce-trailing-comma
      'sonarjs/enforce-trailing-comma'               : 'off',
      'sonarjs/existing-groups'                      : 'error',
      'sonarjs/expression-complexity'                : 'off',
      'sonarjs/file-name-differ-from-class'          : 'off',
      'sonarjs/file-permissions'                     : 'off',
      'sonarjs/file-uploads'                         : 'off',
      'sonarjs/file-header'                          : 'off',
      'sonarjs/fixme-tag'                            : 'warn',
      'sonarjs/for-in'                               : 'warn',
      'sonarjs/for-loop-increment-sign'              : 'error',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/frame-ancestors'                      : 'off',
      'sonarjs/function-inside-loop'                 : 'error',
      // We are using another plugin's rule that's equivalent to function-name
      'sonarjs/function-name'                        : 'off',
      'sonarjs/function-return-type'                 : 'warn',
      'sonarjs/future-reserved-words'                : 'error',
      'sonarjs/generator-without-yield'              : 'warn',
      'sonarjs/hashing'                              : 'warn',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/hidden-files'                         : 'off',
      'sonarjs/in-operator-type-error'               : 'warn',
      'sonarjs/inconsistent-function-call'           : 'error',
      'sonarjs/index-of-compare-to-positive-number'  : 'warn',
      'sonarjs/insecure-cookie'                      : 'error',
      'sonarjs/insecure-jwt-token'                   : 'warn',
      'sonarjs/inverted-assertion-arguments'         : 'warn',
      'sonarjs/jsx-no-leaked-render'                 : 'off',
      'sonarjs/label-position'                       : 'warn',
      'sonarjs/link-with-target-blank'               : 'warn',
      'sonarjs/max-lines'                            : 'off',
      'sonarjs/max-lines-per-function'               : 'off',
      'sonarjs/max-switch-cases'                     : 'warn',
      'sonarjs/max-union-size'                       : 'off',
      'sonarjs/misplaced-loop-counter'               : 'warn',
      'sonarjs/nested-control-flow'                  : 'off',
      'sonarjs/new-operator-misuse'                  : 'warn',
      'sonarjs/no-all-duplicated-branches'           : 'error',
      'sonarjs/no-alphabetical-sort'                 : 'off',
      'sonarjs/no-angular-bypass-sanitization'       : 'off',
      'sonarjs/no-array-delete'                      : 'off',
      'sonarjs/no-associative-arrays'                : 'warn',
      'sonarjs/no-async-constructor'                 : 'error',
      'sonarjs/no-built-in-override'                 : 'error',
      'sonarjs/no-case-label-in-switch'              : 'warn',
      'sonarjs/no-clear-text-protocols'              : 'warn',
      'sonarjs/no-code-after-done'                   : 'error',
      'sonarjs/no-collapsible-if'                    : 'off',
      'sonarjs/no-collection-size-mischeck'          : 'error',
      'sonarjs/no-commented-code'                    : 'warn',
      'sonarjs/no-control-regex'                     : 'error',
      'sonarjs/no-dead-store'                        : 'error',
      'sonarjs/no-delete-var'                        : 'warn',
      'sonarjs/no-duplicate-in-composite'            : 'error',
      'sonarjs/no-duplicate-string'                  : 'off',
      'sonarjs/no-duplicated-branches'               : 'warn',
      'sonarjs/no-element-overwrite'                 : 'warn',
      'sonarjs/no-empty-after-reluctant'             : 'warn',
      'sonarjs/no-empty-alternatives'                : 'off',
      'sonarjs/no-empty-character-class'             : 'warn',
      'sonarjs/no-empty-collection'                  : 'warn',
      'sonarjs/no-empty-group'                       : 'warn',
      'sonarjs/no-empty-test-file'                   : 'error',
      'sonarjs/no-equals-in-for-termination'         : 'warn',
      'sonarjs/no-exclusive-tests'                   : 'error',
      'sonarjs/no-extra-arguments'                   : 'warn',
      'sonarjs/no-fallthrough'                       : 'error',
      'sonarjs/no-for-in-iterable'                   : 'warn',
      'sonarjs/no-function-declaration-in-block'     : 'warn',
      'sonarjs/no-global-this'                       : 'error',
      'sonarjs/no-globals-shadowing'                 : 'warn',
      'sonarjs/no-gratuitous-expressions'            : 'warn',
      'sonarjs/no-hardcoded-ip'                      : 'off',
      'sonarjs/no-hardcoded-passwords'               : 'off',
      'sonarjs/no-hardcoded-secrets'                 : 'warn',
      'sonarjs/no-hook-setter-in-body'               : 'error',
      'sonarjs/no-implicit-dependencies'             : 'error',
      'sonarjs/no-identical-conditions'              : 'warn',
      'sonarjs/no-identical-expressions'             : 'warn',
      'sonarjs/no-identical-functions'               : 'off',
      'sonarjs/no-ignored-exceptions'                : 'warn',
      'sonarjs/no-ignored-return'                    : 'warn',
      'sonarjs/no-implicit-global'                   : 'error',
      'sonarjs/no-in-misuse'                         : 'error',
      'sonarjs/no-incomplete-assertions'             : 'off',
      'sonarjs/no-inconsistent-returns'              : 'error',
      'sonarjs/no-incorrect-string-concat'           : 'off',
      'sonarjs/no-internal-api-use'                  : 'warn',
      'sonarjs/no-intrusive-permissions'             : 'off',
      'sonarjs/no-invalid-await'                     : 'error',
      'sonarjs/no-invalid-regexp'                    : 'error',
      'sonarjs/no-invariant-returns'                 : 'off',
      'sonarjs/no-inverted-boolean-check'            : 'warn',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/no-ip-forward'                        : 'off',
      'sonarjs/no-labels'                            : 'warn',
      'sonarjs/no-literal-call'                      : 'error',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/no-mime-sniff'                        : 'warn',
      'sonarjs/no-misleading-array-reverse'          : 'error',
      'sonarjs/no-misleading-character-class'        : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/no-mixed-content'                     : 'off',
      'sonarjs/no-nested-assignment'                 : 'warn',
      'sonarjs/no-nested-conditional'                : 'off',
      'sonarjs/no-nested-functions'                  : 'warn',
      'sonarjs/no-nested-incdec'                     : 'off',
      'sonarjs/no-nested-switch'                     : 'off',
      'sonarjs/no-nested-template-literals'          : 'off',
      'sonarjs/no-one-iteration-loop'                : 'error',
      'sonarjs/no-os-command-from-path'              : 'warn',
      'sonarjs/no-parameter-reassignment'            : 'warn',
      'sonarjs/no-primitive-wrappers'                : 'warn',
      'sonarjs/no-redundant-assignments'             : 'off',
      'sonarjs/no-redundant-boolean'                 : 'warn',
      'sonarjs/no-redundant-jump'                    : 'warn',
      'sonarjs/no-redundant-optional'                : 'warn',
      'sonarjs/no-redundant-parentheses'             : 'off',
      // Need to fix the environment before I turn this on.
      'sonarjs/no-reference-error'                   : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/no-referrer-policy'                   : 'warn',
      'sonarjs/no-regex-spaces'                      : 'off',
      'sonarjs/no-require-or-define'                 : 'error',
      'sonarjs/no-return-type-any'                   : 'warn',
      'sonarjs/no-same-argument-assert'              : 'warn',
      'sonarjs/no-same-line-conditional'             : 'warn',
      'sonarjs/no-selector-parameter'                : 'warn',
      'sonarjs/no-skipped-tests'                     : 'warn',
      'sonarjs/no-small-switch'                      : 'warn',
      'sonarjs/no-sonar-comments'                    : 'off',
      'sonarjs/no-tab'                               : 'off',
      'sonarjs/no-table-as-layout'                   : 'off',
      'sonarjs/no-try-promise'                       : 'warn',
      'sonarjs/no-undefined-argument'                : 'off',
      'sonarjs/no-undefined-assignment'              : 'off',
      'sonarjs/no-unenclosed-multiline-block'        : 'warn',
      'sonarjs/no-uniq-key'                          : 'error',
      'sonarjs/no-unsafe-unzip'                      : 'off',
      'sonarjs/no-unthrown-error'                    : 'error',
      'sonarjs/no-unused-collection'                 : 'warn',
      'sonarjs/no-unused-function-argument'          : 'off',
      'sonarjs/no-unused-vars'                       : 'off',
      'sonarjs/no-use-of-empty-return-value'         : 'error',
      'sonarjs/no-useless-catch'                     : 'warn',
      'sonarjs/no-useless-increment'                 : 'warn',
      'sonarjs/no-useless-intersection'              : 'error',
      'sonarjs/no-useless-react-setstate'            : 'warn',
      'sonarjs/no-variable-usage-before-declaration' : 'error',
      // Not using Vue
      'sonarjs/no-vue-bypass-sanitization'           : 'off',
      'sonarjs/no-weak-cipher'                       : 'warn',
      'sonarjs/no-weak-keys'                         : 'warn',
      'sonarjs/no-wildcard-import'                   : 'off',
      'sonarjs/non-existent-operator'                : 'error',
      'sonarjs/non-number-in-arithmetic-expression'  : 'warn',
      'sonarjs/null-dereference'                     : 'warn',
      'sonarjs/object-alt-content'                   : 'off',
      'sonarjs/operation-returning-nan'              : 'warn',
      'sonarjs/os-command'                           : 'warn',
      'sonarjs/post-message'                         : 'warn',
      'sonarjs/prefer-default-last'                  : 'warn',
      'sonarjs/prefer-immediate-return'              : 'warn',
      'sonarjs/prefer-object-literal'                : 'off',
      'sonarjs/prefer-promise-shorthand'             : 'error',
      // TODO: Run this up to error and fix, but for now..
      'sonarjs/prefer-read-only-props'               : 'off',
      // There's a rule in regexp for this.
      'sonarjs/prefer-regexp-exec'                   : 'off',
      // May turn this on later.
      'sonarjs/prefer-type-guard'                    : 'off',
      'sonarjs/prefer-single-boolean-return'         : 'warn',
      'sonarjs/prefer-while'                         : 'warn',
      'sonarjs/process-argv'                         : 'off',
      // Express.js rule.
      'sonarjs/production-debug'                     : 'off',
      'sonarjs/pseudo-random'                        : 'off',
      'sonarjs/public-static-readonly'               : 'error',
      'sonarjs/publicly-writable-directories'        : 'off',
      'sonarjs/reduce-initial-value'                 : 'off',
      // only do when we want high-level checks.
      'sonarjs/redundant-type-aliases'               : 'warn',
      // Might turn on later.
      'sonarjs/regex-complexity'                     : 'off',
      'sonarjs/regular-expr'                         : 'off',
      'sonarjs/session-regeneration'                 : 'off',
      'sonarjs/shorthand-property-grouping'          : 'warn',
      'sonarjs/single-char-in-character-classes'     : 'warn',
      'sonarjs/single-character-alternation'         : 'warn',
      'sonarjs/slow-regex'                           : 'warn',
      'sonarjs/sockets'                              : 'off',
      'sonarjs/sql-queries'                          : 'warn',
      'sonarjs/stable-tests'                         : 'warn',
      'sonarjs/standard-input'                       : 'off',
      'sonarjs/stateful-regex'                       : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/strict-transport-security'            : 'warn',
      'sonarjs/strings-comparison'                   : 'warn',
      // VSCode already warns me of this one.
      'sonarjs/super-invocation'                     : 'off',
      'sonarjs/table-header'                         : 'off',
      'sonarjs/table-header-reference'               : 'off',
      'sonarjs/test-check-exception'                 : 'warn',
      'sonarjs/todo-tag'                             : 'off',
      'sonarjs/too-many-break-or-continue-in-loop'   : 'off',
      'sonarjs/updated-const-var'                    : 'off',
      'sonarjs/updated-loop-counter'                 : 'warn',
      'sonarjs/unicode-aware-regex'                  : 'off',
      'sonarjs/unused-import'                        : 'warn',
      'sonarjs/unused-named-groups'                  : 'off',
      'sonarjs/unverified-certificate'               : 'warn',
      'sonarjs/unverified-hostname'                  : 'warn',
      'sonarjs/use-type-alias'                       : 'off',
      'sonarjs/useless-string-operation'             : 'warn',
      'sonarjs/variable-name'                        : 'off',
      'sonarjs/values-not-convertible-to-numbers'    : 'warn',
      'sonarjs/void-use'                             : 'warn',
      'sonarjs/weak-ssl'                             : 'error',
      'sonarjs/web-sql-database'                     : 'off',
      // This rule refer to Express.js, so may not be of benefit.
      'sonarjs/x-powered-by'                         : 'off',
      'sonarjs/xml-parser-xxe'                       : 'off',
      'sonarjs/xpath'                                : 'off',
    },
  },
]

/* eslint-disable-next-line import-x/no-default-export */
export default SonarConfig

