/* SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2025 Curtis Jewell and other contributors
 */
import sonarjs from 'eslint-plugin-sonarjs'
import type { ConfigArray } from 'typescript-eslint'

/**
 * Define the configuration for the sonarjs plugin.
 */
const SonarConfig: ConfigArray = [
  {
    files   : ['**/*{js,ts}'],
    plugins : { sonarjs, },
    rules   : {
      // ...sonarjs.configs.recommended.rules,

      /*
      'cookies': index_js_76.rule,
      'null-dereference': index_js_77.rule,
      'no-selector-parameter': index_js_78.rule,
      'updated-loop-counter': index_js_79.rule,
      'block-scoped-var': index_js_80.rule,
      'no-built-in-override': index_js_81.rule,
      'prefer-object-literal': index_js_82.rule,
      'no-ignored-exceptions': index_js_83.rule,
      'no-gratuitous-expressions': index_js_84.rule,
      'file-uploads': index_js_85.rule,
      'file-permissions': index_js_86.rule,
      'no-empty-character-class': index_js_87.rule,
      'no-unenclosed-multiline-block': index_js_88.rule,
      'index-of-compare-to-positive-number': index_js_89.rule,
      'assertions-in-tests': index_js_90.rule,
      'no-implicit-global': index_js_91.rule,
      'no-useless-catch': index_js_92.rule,
      'xml-parser-xxe': index_js_93.rule,
      'non-existent-operator': index_js_94.rule,
      'web-sql-database': index_js_95.rule,
      'post-message': index_js_96.rule,
      'no-array-delete': index_js_97.rule,
      'no-alphabetical-sort': index_js_98.rule,
      'no-incomplete-assertions': index_js_99.rule,
      'no-global-this': index_js_100.rule,
      */
      /*
      'new-operator-misuse': index_js_101.rule,
      'no-delete-var': index_js_102.rule,
      'strings-comparison': index_js_103.rule,
      'file-name-differ-from-class': index_js_104.rule,
      'cookie-no-httponly': index_js_105.rule,
      'no-nested-conditional': index_js_106.rule,
      'no-incorrect-string-concat': index_js_107.rule,
      'different-types-comparison': index_js_108.rule,
      'inverted-assertion-arguments': index_js_109.rule,
      'shorthand-property-grouping': index_js_110.rule,
      'updated-const-var': index_js_111.rule,
      'arguments-usage': index_js_112.rule,
      'destructuring-assignment-syntax': index_js_113.rule,
      'no-invariant-returns': index_js_114.rule,
      'arrow-function-convention': index_js_115.rule,
      'class-prototype': index_js_116.rule,
      'generator-without-yield': index_js_117.rule,
      'no-require-or-define': index_js_118.rule,
      'no-associative-arrays': index_js_119.rule,
      'comma-or-logical-or-case': index_js_120.rule,
      'no-redundant-jump': index_js_121.rule,
      'inconsistent-function-call': index_js_122.rule,
      'no-use-of-empty-return-value': index_js_123.rule,
      'enforce-trailing-comma': index_js_124.rule,
      'void-use': index_js_125.rule,
      */
      /*
      'operation-returning-nan': index_js_126.rule,
      'values-not-convertible-to-numbers': index_js_127.rule,
      'non-number-in-arithmetic-expression': index_js_128.rule,
      'cognitive-complexity': index_js_129.rule,
      'argument-type': index_js_130.rule,
      'in-operator-type-error': index_js_131.rule,
      'array-callback-without-return': index_js_132.rule,
      'declarations-in-global-scope': index_js_133.rule,
      'function-return-type': index_js_134.rule,
      'no-inconsistent-returns': index_js_135.rule,
      'no-reference-error': index_js_136.rule,
      'super-invocation': index_js_137.rule,
      'no-all-duplicated-branches': index_js_138.rule,
      'no-same-line-conditional': index_js_139.rule,
      'conditional-indentation': index_js_140.rule,
      'no-collection-size-mischeck': index_js_141.rule,
      'no-unthrown-error': index_js_142.rule,
      'no-unused-collection': index_js_143.rule,
      'no-os-command-from-path': index_js_144.rule,
      'no-misleading-array-reverse': index_js_145.rule,
      'no-invalid-await': index_js_146.rule,
      'no-for-in-iterable': index_js_147.rule,
      'no-element-overwrite': index_js_148.rule,
      'no-identical-functions': index_js_149.rule,
      'no-empty-collection': index_js_150.rule,
      */
      /*
      'no-redundant-assignments': index_js_151.rule,
      'prefer-type-guard': index_js_152.rule,
      'use-type-alias': index_js_153.rule,
      'no-return-type-any': index_js_154.rule,
      'no-implicit-dependencies': index_js_155.rule,
      'no-useless-intersection': index_js_156.rule,
      'weak-ssl': index_js_157.rule,
      'no-weak-keys': index_js_158.rule,
      'csrf': index_js_159.rule,
      'production-debug': index_js_160.rule,
      'prefer-default-last': index_js_161.rule,
      'no-in-misuse': index_js_162.rule,
      'no-duplicate-in-composite': index_js_163.rule,
      'max-union-size': index_js_164.rule,
      'no-undefined-argument': index_js_165.rule,
      'no-nested-template-literals': index_js_166.rule,
      'prefer-promise-shorthand': index_js_167.rule,
      'os-command': index_js_168.rule,
      'no-redundant-optional': index_js_169.rule,
      'regular-expr': index_js_170.rule,
      'encryption': index_js_171.rule,
      'hashing': index_js_172.rule,
      'bool-param-default': index_js_173.rule,
      'xpath': index_js_174.rule,
      'sockets': index_js_175.rule,
      */
      /*
      'no-try-promise': index_js_176.rule,
      'process-argv': index_js_177.rule,
      'standard-input': index_js_178.rule,
      'unverified-certificate': index_js_179.rule,
      'no-unsafe-unzip': index_js_180.rule,
      'cors': index_js_181.rule,
      'link-with-target-blank': index_js_182.rule,
      'disabled-auto-escaping': index_js_183.rule,
      'table-header': index_js_184.rule,
      'no-table-as-layout': index_js_185.rule,
      'table-header-reference': index_js_186.rule,
      'object-alt-content': index_js_187.rule,
      'no-clear-text-protocols': index_js_188.rule,
      'publicly-writable-directories': index_js_189.rule,
      'unverified-hostname': index_js_190.rule,
      'encryption-secure-mode': index_js_191.rule,
      'no-weak-cipher': index_js_192.rule,
      'no-intrusive-permissions': index_js_193.rule,
      'insecure-jwt-token': index_js_194.rule,
      'x-powered-by': index_js_195.rule,
      'hidden-files': index_js_196.rule,
      'content-length': index_js_197.rule,
      'disabled-resource-integrity': index_js_198.rule,
      'content-security-policy': index_js_199.rule,
      'no-mixed-content': index_js_200.rule,
      */
      /*
      'frame-ancestors': index_js_201.rule,
      'no-mime-sniff': index_js_202.rule,
      'no-referrer-policy': index_js_203.rule,
      'strict-transport-security': index_js_204.rule,
      'certificate-transparency': index_js_205.rule,
      'dns-prefetching': index_js_206.rule,
      'confidential-information-logging': index_js_207.rule,
      'no-ip-forward': index_js_208.rule,
      'empty-string-repetition': index_js_209.rule,
      'regex-complexity': index_js_210.rule,
      'anchor-precedence': index_js_211.rule,
      'slow-regex': index_js_212.rule,
      'no-invalid-regexp': index_js_213.rule,
      'unused-named-groups': index_js_214.rule,
      'no-same-argument-assert': index_js_215.rule,
      'unicode-aware-regex': index_js_216.rule,
      'no-misleading-character-class': index_js_217.rule,
      'duplicates-in-character-class': index_js_218.rule,
      'session-regeneration': index_js_219.rule,
      'test-check-exception': index_js_220.rule,
      'stable-tests': index_js_221.rule,
      'no-empty-after-reluctant': index_js_222.rule,
      'single-character-alternation': index_js_223.rule,
      'no-code-after-done': index_js_224.rule,
      'disabled-timeout': index_js_225.rule,
      */
      /*
      'no-empty-alternatives': index_js_243.rule,
      'no-control-regex': index_js_244.rule,
      'no-regex-spaces': index_js_245.rule,
      'existing-groups': index_js_247.rule,
      'no-empty-group': index_js_250.rule,
      'stateful-regex': index_js_253.rule,
      'concise-regex': index_js_254.rule,
      'single-char-in-character-classes': index_js_255.rule,
      'no-hardcoded-secrets': index_js_256.rule,
      'no-exclusive-tests': index_js_257.rule,
      'no-hook-setter-in-body': index_js_259.rule,
      'no-useless-react-setstate': index_js_260.rule,
      'no-uniq-key': index_js_261.rule,
      'redundant-type-aliases': index_js_262.rule,
      'prefer-regexp-exec': index_js_263.rule,
      'no-internal-api-use': index_js_264.rule,
      'prefer-read-only-props': index_js_265.rule,
      'no-literal-call': index_js_266.rule,
      'reduce-initial-value': index_js_267.rule,
      'no-async-constructor': index_js_268.rule,
      */

      'sonarjs/arguments-order'                      : 'warn',
      'sonarjs/array-constructor'                    : 'warn',
      'sonarjs/aws-apigateway-public-api'            : 'off',
      'sonarjs/aws-ec2-rds-dms-public'               : 'off',
      'sonarjs/aws-ec2-unencrypted-ebs-volume'       : 'off',
      'sonarjs/aws-efs-unencrypted'                  : 'off',
      'sonarjs/aws-iam-all-privileges'               : 'off',
      'sonarjs/aws-iam-all-resources-accessible'     : 'off',
      'sonarjs/aws-iam-privilege-escalation'         : 'off',
      'sonarjs/aws-iam-public-access'                : 'off',
      'sonarjs/aws-opensearchservice-domain'         : 'off',
      'sonarjs/aws-rds-unencrypted-databases'        : 'off',
      'sonarjs/aws-restricted-ip-admin-access'       : 'off',
      'sonarjs/aws-s3-bucket-granted-access'         : 'off',
      'sonarjs/aws-s3-bucket-insecure-http'          : 'off',
      'sonarjs/aws-s3-bucket-public-access'          : 'off',
      'sonarjs/aws-s3-bucket-server-encryption'      : 'off',
      'sonarjs/aws-s3-bucket-versioning'             : 'off',
      'sonarjs/aws-sagemaker-unencrypted-notebook'   : 'off',
      'sonarjs/aws-sns-unencrypted-topics'           : 'off',
      'sonarjs/aws-sqs-unencrypted-queue'            : 'off',
      'sonarjs/bitwise-operators'                    : 'error',
      'sonarjs/call-argument-line'                   : 'off',
      'sonarjs/chai-determinate-assertion'           : 'off',
      'sonarjs/class-name'                           : 'warn',
      'sonarjs/code-eval'                            : 'error',
      'sonarjs/cognitive-complexity'                 : 'off',
      'sonarjs/comment-regex'                        : 'off',
      'sonarjs/constructor-for-side-effects'         : 'error',
      // TODO: Turn this one on - but have to find out how to configure it.
      'sonarjs/cyclomatic-complexity'                : 'off',
      'sonarjs/deprecation'                          : 'warn',
      'sonarjs/elseif-without-else'                  : 'off',
      'sonarjs/expression-complexity'                : 'off',
      'sonarjs/file-header'                          : 'off',
      'sonarjs/fixme-tag'                            : 'warn',
      'sonarjs/for-in'                               : 'warn',
      'sonarjs/for-loop-increment-sign'              : 'error',
      'sonarjs/function-inside-loop'                 : 'error',
      // We are using another plugin's rule that's equivalent to function-name
      'sonarjs/function-name'                        : 'off',
      'sonarjs/function-return-type'                 : 'warn',
      'sonarjs/future-reserved-words'                : 'error',
      'sonarjs/insecure-cookie'                      : 'error',
      'sonarjs/jsx-no-leaked-render'                 : 'off',
      'sonarjs/label-position'                       : 'warn',
      'sonarjs/max-lines'                            : 'off',
      'sonarjs/max-lines-per-function'               : 'off',
      'sonarjs/max-switch-cases'                     : 'warn',
      'sonarjs/misplaced-loop-counter'               : 'warn',
      'sonarjs/nested-control-flow'                  : 'off',
      'sonarjs/no-angular-bypass-sanitization'       : 'off',
      'sonarjs/no-case-label-in-switch'              : 'warn',
      'sonarjs/no-clear-text-protocols'              : 'warn',
      'sonarjs/no-collapsible-if'                    : 'off',
      'sonarjs/no-commented-code'                    : 'warn',
      'sonarjs/no-dead-store'                        : 'error',
      'sonarjs/no-duplicate-string'                  : 'off',
      'sonarjs/no-duplicated-branches'               : 'warn',
      'sonarjs/no-empty-test-file'                   : 'error',
      'sonarjs/no-equals-in-for-termination'         : 'warn',
      'sonarjs/no-extra-arguments'                   : 'warn',
      'sonarjs/no-fallthrough'                       : 'error',
      'sonarjs/no-function-declaration-in-block'     : 'warn',
      'sonarjs/no-globals-shadowing'                 : 'warn',
      'sonarjs/no-hardcoded-ip'                      : 'off',
      'sonarjs/no-hardcoded-passwords'               : 'off',
      'sonarjs/no-identical-conditions'              : 'warn',
      'sonarjs/no-identical-expressions'             : 'warn',
      'sonarjs/no-ignored-exceptions'                : 'warn',
      'sonarjs/no-ignored-return'                    : 'warn',
      'sonarjs/no-inverted-boolean-check'            : 'warn',
      'sonarjs/no-labels'                            : 'warn',
      'sonarjs/no-nested-assignment'                 : 'warn',
      'sonarjs/no-nested-conditional'                : 'off',
      'sonarjs/no-nested-functions'                  : 'warn',
      'sonarjs/no-nested-incdec'                     : 'off',
      'sonarjs/no-nested-switch'                     : 'off',
      'sonarjs/no-one-iteration-loop'                : 'error',
      'sonarjs/no-parameter-reassignment'            : 'warn',
      'sonarjs/no-primitive-wrappers'                : 'warn',
      'sonarjs/no-redundant-boolean'                 : 'warn',
      'sonarjs/no-redundant-parentheses'             : 'off',
      'sonarjs/no-skipped-tests'                     : 'warn',
      'sonarjs/no-small-switch'                      : 'warn',
      'sonarjs/no-sonar-comments'                    : 'off',
      'sonarjs/no-tab'                               : 'off',
      'sonarjs/no-undefined-assignment'              : 'off',
      'sonarjs/no-unused-function-argument'          : 'off',
      'sonarjs/no-unused-vars'                       : 'off',
      'sonarjs/no-useless-increment'                 : 'warn',
      'sonarjs/no-variable-usage-before-declaration' : 'error',
      'sonarjs/no-vue-bypass-sanitization'           : 'off',
      'sonarjs/no-wildcard-import'                   : 'off',
      'sonarjs/prefer-immediate-return'              : 'warn',
      'sonarjs/prefer-single-boolean-return'         : 'warn',
      'sonarjs/prefer-while'                         : 'warn',
      'sonarjs/pseudo-random'                        : 'off',
      'sonarjs/public-static-readonly'               : 'error',
      'sonarjs/sql-queries'                          : 'warn',
      'sonarjs/todo-tag'                             : 'off',
      'sonatjs/too-many-break-or-continue-in-loop'   : 'off',
      'sonarjs/unused-import'                        : 'warn',
      'sonarjs/useless-string-operation'             : 'warn',
      'sonarjs/variable-name'                        : 'off',
    },
  },
]

/* eslint-disable-next-line import-x/no-default-export */
export default SonarConfig

