/* SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2025 Curtis Jewell and other contributors
 */
import tseslint, { type InfiniteDepthConfigWithExtends } from 'typescript-eslint'

/** Define the rules from typescript-eslint we want to follow. */
const TypescriptConfig: Array<InfiniteDepthConfigWithExtends> = [
  {
    files   : ['**/*.ts'],
    plugins : {
      '@typescript-eslint' : tseslint.plugin,
    },
    rules : {
      'constructor-super'                 : 'off',
      'getter-return'                     : 'off',
      'no-class-assign'                   : 'off',
      'no-const-assign'                   : 'off',
      'no-dupe-args'                      : 'off',
      'no-dupe-class-members'             : 'off',
      'no-dupe-keys'                      : 'off',
      'no-func-assign'                    : 'off',
      'no-import-assign'                  : 'off',
      'no-new-symbol'                     : 'off',
      'no-obj-calls'                      : 'off',
      'no-redeclare'                      : 'off',
      'no-setter-return'                  : 'off',
      'no-this-before-super'              : 'off',
      'no-undef'                          : 'off',
      'no-unreachable'                    : 'off',
      'no-unsafe-negation'                : 'off',
      // ts transpiles let/const to var, so no need for vars any more
      'no-var'                            : 'error',
      'no-with'                           : 'off',
      // ts provides better types with const
      'prefer-const'                      : 'error',
      // ts provides better types with rest args over arguments
      'prefer-rest-params'                : 'error',
      // ts transpiles spread to apply, so no need for manual apply
      'prefer-spread'                     : 'error',
      '@typescript-eslint/array-type'     : [ 'warn', { default: 'generic', }],
      '@typescript-eslint/await-thenable' : 'error',
      '@typescript-eslint/ban-ts-comment' : [
        'error',
        {
          'minimumDescriptionLength' : 10,
          'ts-expect-error'          : false,
          'ts-ignore'                : true,
          'ts-nocheck'               : false,
          'ts-check'                 : false,
        },
      ],
      'no-array-constructor'                           : 'off',
      '@typescript-eslint/consistent-type-assertions'  : 'error',
      '@typescript-eslint/consistent-type-definitions' : [ 'warn', 'type' ],
      '@typescript-eslint/consistent-type-imports'     : [ 'error', { fixStyle: 'inline-type-imports', }],
      '@typescript-eslint/consistent-type-exports'     : [
        'error',
        {
          fixMixedExportsWithInlineTypeSpecifier : true,
        },
      ],
      '@typescript-eslint/default-param-last'             : 'error',
      '@typescript-eslint/dot-notation'                   : 'error',
      '@typescript-eslint/explicit-module-boundary-types' : 'error',
      '@typescript-eslint/method-signature-style'         : 'error',
      '@typescript-eslint/naming-convention'              : [
        'warn',
        {
          selector           : 'default',
          format             : ['camelCase'],
          leadingUnderscore  : 'allow',
          trailingUnderscore : 'forbid',
        },
        {
          selector           : 'variable',
          types              : [ 'string', 'number' ],
          format             : [ 'camelCase', 'UPPER_CASE' ],
          modifiers          : ['const'],
          leadingUnderscore  : 'allow',
          trailingUnderscore : 'forbid',
        },
        {
          selector           : 'variable',
          types              : ['function'],
          format             : [ 'camelCase', 'PascalCase' ],
          modifiers          : ['const'],
          leadingUnderscore  : 'allow',
          trailingUnderscore : 'forbid',
        },
        {
          selector           : 'variable',
          format             : ['PascalCase'],
          modifiers          : ['exported'],
          leadingUnderscore  : 'forbid',
          trailingUnderscore : 'forbid',
        },
        {
          selector           : 'objectLiteralProperty',
          format             : null,
          leadingUnderscore  : 'allowSingleOrDouble',
          trailingUnderscore : 'forbid',
        },
        {
          selector           : 'typeLike',
          format             : ['PascalCase'],
          leadingUnderscore  : 'allow',
          trailingUnderscore : 'forbid',
        },
        {
          // https://typescript-eslint.io/rules/naming-convention/#enforce-that-boolean-variables-are-prefixed-with-an-allowed-verb
          selector           : 'variable',
          types              : ['boolean'],
          format             : [ 'PascalCase', 'camelCase' ],
          prefix             : [ 'is', 'are', 'has', 'should', 'can' ],
          leadingUnderscore  : 'allow',
          trailingUnderscore : 'forbid',
        },
        {
          selector  : 'variable',
          modifiers : ['destructured'],
          format    : null,
        },
        {
          selector : 'import',
          format   : [ 'camelCase', 'PascalCase' ],
        },
        {
          selector : 'typeProperty',
          format   : null,
        },
      ],
      '@typescript-eslint/no-array-constructor'           : 'off',
      '@typescript-eslint/no-array-delete'                : 'error',
      '@typescript-eslint/no-base-to-string'              : 'error',
      '@typescript-eslint/no-confusing-void-expression'   : 'error',
      '@typescript-eslint/no-deprecated'                  : 'error',
      '@typescript-eslint/no-duplicate-enum-values'       : 'error',
      '@typescript-eslint/no-duplicate-type-constituents' : 'error',
      '@typescript-eslint/no-dynamic-delete'              : 'error',
      '@typescript-eslint/no-empty-function'              : 'error',
      '@typescript-eslint/no-empty-object-type'           : [
        'error',
        {
          allowInterfaces : 'with-single-extends',
        },
      ],
      '@typescript-eslint/no-explicit-any'                         : 'error',
      '@typescript-eslint/no-extra-non-null-assertion'             : 'error',
      '@typescript-eslint/no-extraneous-class'                     : 'error',
      '@typescript-eslint/no-floating-promises'                    : 'error',
      '@typescript-eslint/no-for-in-array'                         : 'error',
      'no-implied-eval'                                            : 'off',
      '@typescript-eslint/no-implied-eval'                         : 'error',
      '@typescript-eslint/no-import-type-side-effects'             : 'error',
      '@typescript-eslint/no-inferrable-types'                     : 'error',
      '@typescript-eslint/no-invalid-void-type'                    : 'error',
      '@typescript-eslint/no-loop-func'                            : 'error',
      '@typescript-eslint/no-meaningless-void-operator'            : 'error',
      '@typescript-eslint/no-misused-new'                          : 'error',
      '@typescript-eslint/no-misused-promises'                     : 'error',
      '@typescript-eslint/no-misused-spread'                       : 'error',
      '@typescript-eslint/no-mixed-enums'                          : 'error',
      '@typescript-eslint/no-namespace'                            : 'error',
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing' : 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain'     : 'error',
      '@typescript-eslint/no-non-null-assertion'                   : 'warn',
      '@typescript-eslint/no-redundant-type-constituents'          : 'error',
      // eventually we will enable unicorn/prefer-module instead:
      // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-module.md
      '@typescript-eslint/no-require-imports'                      : 'off',
      '@typescript-eslint/no-shadow'                               : [
        'error',
        {
          hoist                                      : 'all',
          allow                                      : [ 'resolve', 'reject', 'done', 'next', 'err', 'error' ],
          ignoreTypeValueShadow                      : true,
          ignoreFunctionTypeParameterNameValueShadow : true,
        },
      ],
      '@typescript-eslint/no-this-alias'                          : 'error',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare' : 'error',
      '@typescript-eslint/no-unnecessary-condition'               : 'error',
      '@typescript-eslint/no-unnecessary-template-expression'     : 'error',
      '@typescript-eslint/no-unnecessary-type-arguments'          : 'error',
      '@typescript-eslint/no-unnecessary-type-assertion'          : 'error',
      '@typescript-eslint/no-unnecessary-type-constraint'         : 'error',
      '@typescript-eslint/no-unnecessary-type-parameters'         : 'error',
      '@typescript-eslint/no-unsafe-argument'                     : 'error',
      '@typescript-eslint/no-unsafe-assignment'                   : 'off',
      '@typescript-eslint/no-unsafe-call'                         : 'error',
      '@typescript-eslint/no-unsafe-declaration-merging'          : 'error',
      '@typescript-eslint/no-unsafe-enum-comparison'              : 'error',
      '@typescript-eslint/no-unsafe-function-type'                : 'error',
      '@typescript-eslint/no-unsafe-member-access'                : 'error',
      '@typescript-eslint/no-unsafe-return'                       : 'error',
      '@typescript-eslint/no-unsafe-unary-minus'                  : 'error',
      'no-unused-expressions'                                     : 'off',
      '@typescript-eslint/no-unused-expressions'                  : [
        'error',
        {
          allowShortCircuit    : true,
          allowTernary         : true,
          allowTaggedTemplates : true,
          enforceForJSX        : true,
        },
      ],
      'no-unused-vars'                    : 'off',
      '@typescript-eslint/no-unused-vars' : [
        'warn',
        {
          args                           : 'all',
          argsIgnorePattern              : '^_',
          caughtErrors                   : 'all',
          caughtErrorsIgnorePattern      : '^_',
          destructuredArrayIgnorePattern : '^_',
          varsIgnorePattern              : '^_',
          ignoreRestSiblings             : true,
        },
      ],
      '@typescript-eslint/no-use-before-define'       : 'error',
      'no-useless-constructor'                        : 'off',
      '@typescript-eslint/no-useless-constructor'     : 'error',
      '@typescript-eslint/no-wrapper-object-types'    : 'error',
      'no-throw-literal'                              : 'off',
      '@typescript-eslint/only-throw-error'           : 'error',
      '@typescript-eslint/prefer-as-const'            : 'error',
      '@typescript-eslint/prefer-function-type'       : 'error',
      '@typescript-eslint/prefer-literal-enum-member' : 'error',
      '@typescript-eslint/prefer-namespace-keyword'   : 'error',
      '@typescript-eslint/prefer-nullish-coalescing'  : [
        'error',
        {
          ignorePrimitives : true,
        },
      ],
      '@typescript-eslint/prefer-optional-chain'          : 'error',
      'prefer-promise-reject-errors'                      : 'off',
      '@typescript-eslint/prefer-promise-reject-errors'   : 'error',
      '@typescript-eslint/prefer-reduce-type-parameter'   : 'error',
      '@typescript-eslint/prefer-return-this-type'        : 'error',
      '@typescript-eslint/prefer-string-starts-ends-with' : 'error',
      '@typescript-eslint/related-getter-setter-pairs'    : 'error',
      'require-await'                                     : 'off',
      '@typescript-eslint/require-await'                  : 'error',
      '@typescript-eslint/restrict-plus-operands'         : [
        'error',
        {
          allowAny             : false,
          allowBoolean         : false,
          allowNullish         : false,
          allowNumberAndString : false,
          allowRegExp          : false,
        },
      ],
      '@typescript-eslint/restrict-template-expressions' : [
        'error',
        {
          allowAny     : false,
          allowBoolean : false,
          allowNever   : false,
          allowNullish : false,
          allowNumber  : false,
          allowRegExp  : false,
        },
      ],
      'no-return-await'                 : 'off',
      '@typescript-eslint/return-await' : [
        'error',
        'error-handling-correctness-only',
      ],
      '@typescript-eslint/switch-exhaustiveness-check'            : 'error',
      '@typescript-eslint/triple-slash-reference'                 : 'error',
      '@typescript-eslint/unbound-method'                         : 'error',
      '@typescript-eslint/unified-signatures'                     : 'error',
      '@typescript-eslint/use-unknown-in-catch-callback-variable' : 'off',
    },
  },
  {
    files : ['**/*.js'],
    rules : {
      '@typescript-eslint/await-thenable' : 'off',
      '@typescript-eslint/ban-ts-comment' : [
        'error',
        {
          'minimumDescriptionLength' : 10,
          'ts-expect-error'          : false,
          'ts-ignore'                : true,
          'ts-nocheck'               : false,
          'ts-check'                 : false,
        },
      ],
      '@typescript-eslint/consistent-return'       : 'off',
      '@typescript-eslint/consistent-type-imports' : [
        'error',
        { fixStyle: 'inline-type-imports', },
      ],
      '@typescript-eslint/consistent-type-exports'        : 'off',
      '@typescript-eslint/default-param-last'             : 'error',
      '@typescript-eslint/dot-notation'                   : 'off',
      '@typescript-eslint/explicit-module-boundary-types' : 'off',
      '@typescript-eslint/method-signature-style'         : 'error',
      '@typescript-eslint/naming-convention'              : 'off',
      '@typescript-eslint/no-array-constructor'           : 'off',
      '@typescript-eslint/no-array-delete'                : 'off',
      '@typescript-eslint/no-base-to-string'              : 'off',
      '@typescript-eslint/no-confusing-void-expression'   : 'off',
      '@typescript-eslint/no-deprecated'                  : 'off',
      '@typescript-eslint/no-duplicate-enum-values'       : 'error',
      '@typescript-eslint/no-duplicate-type-constituents' : 'off',
      '@typescript-eslint/no-dynamic-delete'              : 'error',
      '@typescript-eslint/no-empty-function'              : 'error',
      '@typescript-eslint/no-empty-object-type'           : [
        'error',
        {
          allowInterfaces : 'with-single-extends',
        },
      ],
      '@typescript-eslint/no-explicit-any'                         : 'error',
      '@typescript-eslint/no-extra-non-null-assertion'             : 'error',
      '@typescript-eslint/no-extraneous-class'                     : 'error',
      '@typescript-eslint/no-floating-promises'                    : 'off',
      '@typescript-eslint/no-for-in-array'                         : 'off',
      '@typescript-eslint/no-implied-eval'                         : 'off',
      '@typescript-eslint/no-import-type-side-effects'             : 'error',
      '@typescript-eslint/no-inferrable-types'                     : 'error',
      '@typescript-eslint/no-invalid-void-type'                    : 'error',
      '@typescript-eslint/no-loop-func'                            : 'error',
      '@typescript-eslint/no-meaningless-void-operator'            : 'off',
      '@typescript-eslint/no-misused-new'                          : 'error',
      '@typescript-eslint/no-misused-promises'                     : 'off',
      '@typescript-eslint/no-misused-spread'                       : 'off',
      '@typescript-eslint/no-mixed-enums'                          : 'off',
      '@typescript-eslint/no-namespace'                            : 'error',
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing' : 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain'     : 'error',
      '@typescript-eslint/no-non-null-assertion'                   : 'warn',
      '@typescript-eslint/no-redundant-type-constituents'          : 'off',
      // eventually we will enable unicorn/prefer-module instead:
      // https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-module.md
      '@typescript-eslint/no-require-imports'                      : 'off',
      '@typescript-eslint/no-shadow'                               : [
        'error',
        {
          hoist                                      : 'all',
          allow                                      : [ 'resolve', 'reject', 'done', 'next', 'err', 'error' ],
          ignoreTypeValueShadow                      : true,
          ignoreFunctionTypeParameterNameValueShadow : true,
        },
      ],
      '@typescript-eslint/no-this-alias'                          : 'error',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare' : 'off',
      '@typescript-eslint/no-unnecessary-condition'               : 'off',
      '@typescript-eslint/no-unnecessary-qualifier'               : 'off',
      '@typescript-eslint/no-unnecessary-template-expression'     : 'off',
      '@typescript-eslint/no-unnecessary-type-arguments'          : 'off',
      '@typescript-eslint/no-unnecessary-type-constraint'         : 'error',
      '@typescript-eslint/no-unnecessary-type-assertion'          : 'off',
      '@typescript-eslint/no-unnecessary-type-parameters'         : 'off',
      '@typescript-eslint/no-unsafe-argument'                     : 'off',
      '@typescript-eslint/no-unsafe-assignment'                   : 'off',
      '@typescript-eslint/no-unsafe-call'                         : 'off',
      '@typescript-eslint/no-unsafe-declaration-merging'          : 'error',
      '@typescript-eslint/no-unsafe-enum-comparison'              : 'off',
      '@typescript-eslint/no-unsafe-function-type'                : 'error',
      '@typescript-eslint/no-unsafe-member-access'                : 'off',
      '@typescript-eslint/no-unsafe-return'                       : 'off',
      '@typescript-eslint/no-unsafe-type-assertion'               : 'off',
      '@typescript-eslint/no-unsafe-unary-minus'                  : 'off',
      'no-unused-expressions'                                     : 'off',
      '@typescript-eslint/no-unused-expressions'                  : [
        'error',
        {
          allowShortCircuit    : true,
          allowTernary         : true,
          allowTaggedTemplates : true,
          enforceForJSX        : true,
        },
      ],
      '@typescript-eslint/no-unused-vars' : [
        'warn',
        {
          args                           : 'all',
          argsIgnorePattern              : '^_',
          caughtErrors                   : 'all',
          caughtErrorsIgnorePattern      : '^_',
          destructuredArrayIgnorePattern : '^_',
          varsIgnorePattern              : '^_',
          ignoreRestSiblings             : true,
        },
      ],
      '@typescript-eslint/no-use-before-define'                   : 'error',
      'no-useless-constructor'                                    : 'off',
      '@typescript-eslint/no-useless-constructor'                 : 'error',
      '@typescript-eslint/no-wrapper-object-types'                : 'error',
      '@typescript-eslint/non-nullable-type-assertion-style'      : 'off',
      '@typescript-eslint/only-throw-error'                       : 'off',
      '@typescript-eslint/prefer-as-const'                        : 'error',
      '@typescript-eslint/prefer-destructuring'                   : 'off',
      '@typescript-eslint/prefer-find'                            : 'off',
      '@typescript-eslint/prefer-function-type'                   : 'error',
      '@typescript-eslint/prefer-includes'                        : 'off',
      '@typescript-eslint/prefer-literal-enum-member'             : 'error',
      '@typescript-eslint/prefer-namespace-keyword'               : 'error',
      '@typescript-eslint/prefer-nullish-coalescing'              : 'off',
      '@typescript-eslint/prefer-optional-chain'                  : 'off',
      '@typescript-eslint/prefer-promise-reject-errors'           : 'off',
      '@typescript-eslint/prefer-readonly'                        : 'off',
      '@typescript-eslint/prefer-readonly-parameter-types'        : 'off',
      '@typescript-eslint/prefer-reduce-type-parameter'           : 'off',
      '@typescript-eslint/prefer-regexp-exec'                     : 'off',
      '@typescript-eslint/prefer-return-this-type'                : 'off',
      '@typescript-eslint/prefer-string-starts-ends-with'         : 'off',
      '@typescript-eslint/promise-function-async'                 : 'off',
      '@typescript-eslint/related-getter-setter-pairs'            : 'off',
      '@typescript-eslint/require-array-sort-compare'             : 'off',
      '@typescript-eslint/require-await'                          : 'off',
      '@typescript-eslint/restrict-plus-operands'                 : 'off',
      '@typescript-eslint/restrict-template-expressions'          : 'off',
      '@typescript-eslint/return-await'                           : 'off',
      '@typescript-eslint/strict-boolean-expressions'             : 'off',
      '@typescript-eslint/switch-exhaustiveness-check'            : 'off',
      '@typescript-eslint/triple-slash-reference'                 : 'error',
      '@typescript-eslint/unbound-method'                         : 'off',
      '@typescript-eslint/unified-signatures'                     : 'error',
      '@typescript-eslint/use-unknown-in-catch-callback-variable' : 'off',
    },
    languageOptions : {
      parserOptions : { program: null, project: false, projectService: false, },
    },
    plugins : {
      '@typescript-eslint' : tseslint.plugin,
    },
  },
]

/* eslint-disable-next-line import-x/no-default-export */
export default TypescriptConfig
