/*! SPDX-License-Identifier: MIT
 *  SPDX-FileCopyrightText: 2025 Curtis Jewell and other contributors
 */
import { html } from 'htm/preact'
// eslint-disable-next-line import-x/no-deprecated -- Not using the deprecated functionality
import { render } from 'preact'
import App from './src/components/App.ts'
import type { Types } from '@csjewell-activitypub/general'

/**
 * @experimental
 * Show the re-pliers component within an HTML page.
 *
 * @param info - Inforation about the current blog entry.
 * @param info.page - The canonical URL.
 * @param info.user - The local username of the person creating the blog entry.
 * @param info.domain - The domain.
 * @param element - The HTML element to render the re-pliers component within.
 * @param cache - A cache of the non-logged in replies, generated by the static page generator.
 */
export const showRepliers = (
  info: {
    page   : string,
    user   : string,
    domain : string,
  },
  element: HTMLElement,
  cache: Types.ReplyListCtxType,
): void => {
  // eslint-disable-next-line import-x/no-deprecated -- Not using the deprecated functionality
  render(
    html`<${ App } page=${ info.page } user=${ info.user } domain=${ info.domain } cache=${ cache } />`,
    element,
  )
}
