name: Publish
on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Use Node.js 23
        uses: nubjs/setup-nub@47e5e7393d50f4e9544ddaf756aa277972afba2d # v0.4.0
        with:
          nub-version: v0.5.0
          node-version: 24
          cache: true
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: nub install --frozen-lockfile

      - name: Publish all packages to npm
        run: nub publish --tag `bin/npmtag.js`
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish all packages to jsr
        run: nubx -y jsr publish

