name: Publish
on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org


      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish types package to jsr
        run: cd packages/types && cp ../../LICENSES/MIT.txt LICENSE && pnpx jsr publish --provenance

      - name: Publish general package to jsr
        run: cd packages/general && cp ../../LICENSES/MIT.txt LICENSE && pnpx jsr publish --provenance

      - name: Publish eslint-config package to jsr
        run: cd packages/eslint-config && cp ../../LICENSES/MIT.txt LICENSE && pnpx jsr publish --provenance

      - name: Publish types package to npm
        run: cd packages/types && pnpm publish --access public --tag next --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish general package to npm
        run: cd packages/general && pnpm publish --access public --tag next --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish eslint-config package to npm
        run: cd packages/eslint-config && pnpm publish --access public --tag next --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#      - name: Publish database-cloudflare-d1 package to jsr
#        run: cd proposed/database-cloudflare-d1 && pnpm dlx jsr publish

#      - name: Publish workers-cloudflare package to jsr
#        run: cd proposed/workers-cloudflare && pnpm dlx jsr publish

#      - name: Publish handlers-response package to jsr
#        run: cd proposed/handlers-response && pnpm dlx jsr publish
